name: Nocturne Backend
on:
  push:
    branches: ["master"]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: build container
        run: make release
      - name: Tag the image
        run: make tag
      - name: Log in to GitHub Container Registry
        env:
          GHCR_PUSH_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
        run: echo $GHCR_PUSH_TOKEN | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
      - name: Push the image
        run: make push
