name: Nocturne Backend

on:
    push: 
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          docker:
            image: docker:latest
            options: --privileged
    
        steps:
          - name: checkout
            uses: actions/checkout@v2
    
          - name: setup buildx
            uses: docker/setup-buildx-action@v2
    
          - name: build container
            run: |
              docker build -t nocturne-backend -f ./backend/production.containerfile .
