name: Nocturne Frontend
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: build image
        run: make release
      - name: tag image
        run: make tag
      - name: ghcr.io login
        env:
          GHCR_PUSH_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
        run: echo $GHCR_PUSH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: push image
        run: make push
